### ISSUE TITLE
Missing srcs in BUILD

### ISSUE THREAD

**Issue by jondo2010** [bazelboost/iostreams#1]
Thanks for the quick fix on https://github.com/bazelboost/filesystem/issues/3!

Seems like `iostreams` is missing some srcs in it's BUILD definition.

**Comment by zaucy** [comment]
haha yeah there might be a few archives missing the `src` directory. 😅 the script I wrote initially didn't include it. I'll get on this shortly.

**Comment by zaucy** [comment]
should be fixed in `1.83.0.bzl.2`
